---
title: "Comparative Ccognition Graphs for Presentations"
author: "Kelly Wallace"
date: "April 26, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(rmarkdown)
library(knitr)
library(readr)
library(utils)
library(EnvStats)

shuttle<-read.csv("C:/Users/Kelly/Desktop/Grad School/Cummings Lab/Comparative Cognition/Shuttlebox/shuttlebox_data_april_25_2018.csv")

det<-read.csv("C:/Users/Kelly/Desktop/Grad School/Cummings Lab/Comparative Cognition/Detour/detour_data_for_R_April_5_2018.csv")

num<-read.csv("C:/Users/Kelly/Desktop/Grad School/Cummings Lab/Comparative Cognition/Comparative Cognition R Scripts/Numerosity Comparative Cognition Full Dataset April_17_2018.csv")

df.full<- left_join(det,shuttle, by = 'fish_name')
df.full<- left_join(df.full,num, by = 'fish_name')
df.full$detour_trial_1_did_fish_solve_barrier_problem <-as.character(df.full$detour_trial_1_did_fish_solve_barrier_problem)

df<- read_csv("C:/Users/Kelly/Desktop/Grad School/Cummings Lab/Comparative Cognition/Comparative Cognition R Scripts/Numerosity Comparative Cognition Full Dataset April_17_2018.csv", col_names = TRUE, col_types = NULL)

df$number_of_medians_above_60_using_full_4_minutes_data<-as.factor(df$number_of_medians_above_60_using_full_4_minutes_data)
df$number_of_medians_above_60_using_T30_to_T50_data<-as.factor(df$number_of_medians_above_60_using_T30_to_T50_data)


#WRITE IT OUT IF NEEDED
#write_csv(df.full, 'Full_Comparative_Cognition_Data_Detour_Shuttlebox_Numerosity_April_12_2018.csv')
```



```{r, echo=FALSE, message=FALSE}
#Does average latency to enter correct side predict average performance (T30 to T50 data)?
#****************************************************************************** this is the luke set up, use it as a template if needed
mod<- lm(df$average_performance_across_all_9_testing_trials_using_T30_to_T50_data ~ df$average_latency_to_enter_correct_side, na.rm = TRUE)
summary(mod)

number <- df %>% filter(!is.na(average_latency_to_enter_correct_side)) %>% filter(!is.na(average_performance_across_all_9_testing_trials_using_T30_to_T50_data)) %>% nrow
p_value <- mod %>% broom::tidy() %>% filter(term != "(Intercept)") %>% select(p.value) %>% unlist
r_squared <- mod %>% broom::glance() %>% select(r.squared) %>% unlist

p <- ggplot(df, aes(average_latency_to_enter_correct_side, average_performance_across_all_9_testing_trials_using_T30_to_T50_data))
p + geom_point(size = 4) + 
  theme(text = element_text(size=20)) + 
  annotate("text", x=50, y=0.05, label= glue::glue("p = {round(p_value,4)} r-squared =  {round(r_squared,3)} n = {number}"), size = 9, color = "gray23") + 
  labs(x= "Numerosity: average latency to enter correct side",y="Numerosity: Average proportion of 
time spent on the correct side") +
  #ggtitle ("Does average latency to enter correct side predict 
  #         average performance (T30 to T50 data)?") +
  geom_smooth(method = "lm", size = 2, fill = "light gray", color = "lightsteelblue4")+
         theme(axis.text=element_text(size=20),
         axis.title=element_text(size=14))+
         theme(axis.line.y = element_line(color="gray", size = 1))+
         theme(axis.line.x = element_line(color="gray", size = 1))+ 
         theme(panel.background = element_blank())+ 
         #theme(plot.title = element_text(size=20))
         theme(axis.title.x=element_text(size=25, color = "deepskyblue4")) +
         theme(axis.title.y=element_text(size=25, color = "deepskyblue4"))

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Does average number of entries predict average performance (T30 to T50)?

mod<- lm(df$average_performance_across_all_9_testing_trials_using_T30_to_T50_data ~ df$average_number_of_entries, na.rm = TRUE)
summary(mod)

number <- df %>% filter(!is.na(average_performance_across_all_9_testing_trials_using_T30_to_T50_data)) %>% filter(!is.na(average_number_of_entries)) %>% nrow
p_value <- mod %>% broom::tidy() %>% filter(term != "(Intercept)") %>% select(p.value) %>% unlist
r_squared <- mod %>% broom::glance() %>% select(r.squared) %>% unlist

p <- ggplot(df, aes(average_number_of_entries, average_performance_across_all_9_testing_trials_using_T30_to_T50_data, color = sex))
p + geom_point(size = 4) + 
  theme(text = element_text(size=20)) + 
  annotate("text", x=78, y=0.08, label= glue::glue("p = {round(p_value,4)} r-squared =  {round(r_squared,3)} n = {number}"), size = 9, color = "gray23") + 
  labs(x= "Numerosity: average number of entries",y="Numerosity: Average proportion of 
time spent on the correct side") +
  #ggtitle ("Does average number of entries predict average performance (T30 to T50)?") +
  geom_smooth(method = "lm", size = 2, fill = "light gray", color = "lightsteelblue4")+
         theme(axis.text=element_text(size=20),
         axis.title=element_text(size=14))+
         theme(axis.line.y = element_line(color="gray", size = 1))+
         theme(axis.line.x = element_line(color="gray", size = 1))+ 
         theme(panel.background = element_blank())+ 
         #theme(plot.title = element_text(size=20))
         theme(axis.title.x=element_text(size=25, color = "deepskyblue4")) +
         theme(axis.title.y=element_text(size=25, color = "deepskyblue4"))


```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Does size/age predict average number of entries?
mod<- lm(df$average_number_of_entries ~ df$standard_length, na.rm = TRUE)
summary(mod)

number <- df %>% filter(!is.na(average_number_of_entries)) %>% filter(!is.na(standard_length)) %>% nrow
p_value <- mod %>% broom::tidy() %>% filter(term != "(Intercept)") %>% select(p.value) %>% unlist
r_squared <- mod %>% broom::glance() %>% select(r.squared) %>% unlist

p <- ggplot(df, aes(standard_length, average_number_of_entries, color = sex))
p + geom_point(size = 4) + 
  theme(text = element_text(size=20)) + 
  annotate("text", 2100, y=10, label= glue::glue("p = {round(p_value,4)}, r-squared = {round(r_squared,3)} n = {number}"), size = 9, color = "gray23") +
  labs(x= "age (standard length)",y="Numerosity: average number of entries") +
  #ggtitle ("Does size/age predict average number of entries?SEXES COMBINED") +
  geom_smooth(method = "lm", size = 2, fill = "light gray", color = "lightsteelblue4")+
         theme(axis.text=element_text(size=20),
         axis.title=element_text(size=14))+
         theme(axis.line.y = element_line(color="gray", size = 1))+
         theme(axis.line.x = element_line(color="gray", size = 1))+ 
         theme(panel.background = element_blank())+ 
         #theme(plot.title = element_text(size=20))
         theme(axis.title.x=element_text(size=25, color = "deepskyblue4")) +
         theme(axis.title.y=element_text(size=25, color = "deepskyblue4"))


```





```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Does size/age predict average latency to enter correct side?
mod<- lm(df$average_latency_to_enter_correct_side ~ df$standard_length, na.rm = TRUE)
summary(mod)

number <- df %>% filter(!is.na(average_latency_to_enter_correct_side)) %>% filter(!is.na(standard_length)) %>% nrow
p_value <- mod %>% broom::tidy() %>% filter(term != "(Intercept)") %>% select(p.value) %>% unlist
r_squared <- mod %>% broom::glance() %>% select(r.squared) %>% unlist

p <- ggplot(df, aes(standard_length, average_latency_to_enter_correct_side, color = sex))
p + geom_point(size = 4) + 
  theme(text = element_text(size=20)) + 
  annotate("text", x=2300, y=7, label= glue::glue("p = {round(p_value,4)}, r-squared =   {round(r_squared,3)} n = {number}"), size = 9, color = "gray23") + 
  labs(x= "age (standard length)",y="Numerosity: average latency to
       enter the correct side") +
  #ggtitle ("Does size/age predict average latency to enter correct side? SEXES COMBINED") +
  geom_smooth(method = "lm", size = 2, fill = "light gray", color = "lightsteelblue4")+
         theme(axis.text=element_text(size=20),
         axis.title=element_text(size=14))+
         theme(axis.line.y = element_line(color="gray", size = 1))+
         theme(axis.line.x = element_line(color="gray", size = 1))+ 
         theme(panel.background = element_blank())+ 
         #theme(plot.title = element_text(size=20))
         theme(axis.title.x=element_text(size=25, color = "deepskyblue4")) +
         theme(axis.title.y=element_text(size=25, color = "deepskyblue4"))



```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Does Detour category (solved barrier problem versus did not solve barrier problem) predict numerosity performance over T30 to T50?

test<-t.test(df.full$average_performance_across_all_9_testing_trials_using_T30_to_T50_data~df.full$detour_trial_1_did_fish_solve_barrier_problem)
p_value_t<- test %>% broom::tidy() %>% select(p.value) %>% unlist
wilcox_test<-wilcox.test(df.full$average_performance_across_all_9_testing_trials_using_T30_to_T50_data~df.full$detour_trial_1_did_fish_solve_barrier_problem)
p_value_wilcox<-wilcox_test$p.value

p <- ggplot(df.full, aes(x=detour_trial_1_did_fish_solve_barrier_problem, y=average_performance_across_all_9_testing_trials_using_T30_to_T50_data)) + 
  geom_boxplot()+ stat_n_text() +
  #ggtitle('Does Detour category (solved barrier problem versus did not solve 
  #       barrier problem) predict numerosity performance over T30 to T50?') +
  geom_text(x=1, y=0.1, label= glue::glue("p (t-test)= {round(p_value_t,4)}"), size = 9, color = "gray23") +
        theme(axis.text=element_text(size=20),
         axis.title=element_text(size=14))+ 
  labs(x= "Detour: did fish navigate around the barrier?
No (0) Yes (1)",y="Numerosity: Average proportion of 
time spent on the correct side") +
         theme(axis.line.y = element_line(color="gray", size = 1))+
         theme(axis.line.x = element_line(color="gray", size = 1))+ 
         theme(panel.background = element_blank())+ 
         #theme(plot.title = element_text(size=20))
         theme(axis.title.x=element_text(size=25, color = "deepskyblue4")) +
         theme(axis.title.y=element_text(size=25, color = "deepskyblue4"))
p

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Do individual who solve the barrier problem have lower latencies to approach the barrier (higher motivation?)

test<-t.test(df.full$time_to_barrier_contact_minus_start_time~df.full$detour_trial_1_did_fish_solve_barrier_problem)
p_value_t<- test %>% broom::tidy() %>% select(p.value) %>% unlist
wilcox_test<-wilcox.test(df.full$time_to_barrier_contact_minus_start_time~df.full$detour_trial_1_did_fish_solve_barrier_problem)
p_value_wilcox<-wilcox_test$p.value

p <- ggplot(df.full, aes(x=detour_trial_1_did_fish_solve_barrier_problem, y=time_to_barrier_contact_minus_start_time)) + 
  geom_boxplot()+ stat_n_text() +
  #ggtitle('Do individuals who solve the barrier problem have lower latencies 
  #        to approach the barrier (higher motivation?)') +
  geom_text(x=1, y=0.1, label= glue::glue("p (t-test)= {round(p_value_t,4)}"), size = 9, color = "gray23") +
        theme(axis.text=element_text(size=20),
         axis.title=element_text(size=14))+ 
  labs(x= "Detour: did fish navigate around the barrier?
No (0) Yes (1)",y="Detour: latency to approach barrier") +
         theme(axis.line.y = element_line(color="gray", size = 1))+
         theme(axis.line.x = element_line(color="gray", size = 1))+ 
         theme(panel.background = element_blank())+ 
         #theme(plot.title = element_text(size=20))
         theme(axis.title.x=element_text(size=25, color = "deepskyblue4")) +
         theme(axis.title.y=element_text(size=25, color = "deepskyblue4"))
p


```



```{r, echo=FALSE, message=FALSE}
#Does numerosity average performance (T30 to T50) predict shuttlebox slope of the proportion correct side across gaps?
mod<- lm(df.full$shuttlebox_proportion_of_time_on_correct_side_during_gaps_slope_across_presentations ~ df.full$average_performance_across_all_9_testing_trials_using_T30_to_T50_data)
summary(mod)

number <- df.full %>% filter(!is.na(average_performance_across_all_9_testing_trials_using_T30_to_T50_data)) %>% filter(!is.na(shuttlebox_proportion_of_time_on_correct_side_during_gaps_slope_across_presentations)) %>% nrow
p_value <- mod %>% broom::tidy() %>% filter(term != "(Intercept)") %>% select(p.value) %>% unlist
r_squared <- mod %>% broom::glance() %>% select(r.squared) %>% unlist

p <- ggplot(df.full, aes(average_performance_across_all_9_testing_trials_using_T30_to_T50_data, shuttlebox_proportion_of_time_on_correct_side_during_gaps_slope_across_presentations))
p + geom_point(size = 3) + 
  theme(text = element_text(size=10)) + 
  annotate("text", x=0.46, y=-0.018,label= glue::glue("p = {round(p_value,4)}, r-squared = {round(r_squared,3)} n = {number}"), size = 9, color = "gray23") + 
  #ggtitle ("Does numerosity average performance (T30 to T50) predict shuttlebox 
  #         slope of the proportion correct side across gaps") +
          theme(axis.text=element_text(size=20),
         axis.title=element_text(size=14))+ 
  labs(x= "Numerosity: Average proportion of 
time spent on the correct side
",y="Shuttlebox: 'Learning Curve' (slope) 
of proportion time spent on the
correct (anticipatory) side") +
  geom_smooth(method = "lm", size = 2, fill = "light gray", color = "lightsteelblue4")+
         theme(axis.line.y = element_line(color="gray", size = 1))+
         theme(axis.line.x = element_line(color="gray", size = 1))+ 
         theme(panel.background = element_blank())+ 
         #theme(plot.title = element_text(size=20))
         theme(axis.title.x=element_text(size=25, color = "deepskyblue4")) +
         theme(axis.title.y=element_text(size=25, color = "deepskyblue4"))+
  coord_cartesian(xlim=c(0.2,0.7))

```

